server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8arsdn7f7vs738mq31g-a.oregon-postgres.render.com:5432/portfolio_xeil
spring.datasource.username=portfolio_xeil_user
spring.datasource.password=v4JyrMnP4aoDz3PhUbTMuNRHFJgiFZsG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
