server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8arerel51nc73f6i1b0-a:5432/portfolio_cj6b
spring.datasource.username=portfolio_cj6b_user
spring.datasource.password=v4JyrMnP4aoDz3PhUbTMuNRHFJgiFZsG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect